### ISSUE TITLE
dalaodalao，有没有Python方式获取的，调用sunnydll那种。

### ISSUE THREAD

**Issue by ASCIIX** [LauZzL/sid4ltzj#1]
dalaodalao，有没有Python方式获取的，调用sunnydll那种。
![Uploading 123.jpg…]()

**Comment by LauZzL** [comment]
当然！[look at this example](https://wwxa.lanzouj.com/iUy2n28jk2ob)

你只需要在`Demo.py` 中的 `Callback.Http`  方法，将 `body = SyHTTP.请求.取POST数据_字节数组()` 添加到 `消息类型 == Callback.Http_消息类型_发起请求` if 判断中

并使用base64编码将 `body` 编码后发送到Node服务即可

like this:

```python
# 获取到POST提交的数据
body = SyHTTP.请求.取POST数据_字节数组()
# 替换为你自己的工具类
base64_data = utils.base64_encode(body)
print('解密后数据', commonRequest.request('d', base64_data))
```

commonRequest.py:

```python
import requests
# import utils
# from config.config import settings

def request(uri, data):
    # your node server
    url = settings.node_server.format(uri)
    headers = {
        "Content-Type": "application/json",
    }
    payload = {
        "data": data
    }
    response = requests.post(url, data=payload, headers=headers)
    return response.text
```

**Comment by ASCIIX** [comment]
好的大佬，我先看看
![123](https://github.com/user-attachments/assets/d1697064-46bd-4069-bd85-cd7eaba4219a)

**Comment by ASCIIX** [comment]
大佬，大佬，已经研究出来了，怎么和V1一样，把环境打包成软件，放Python里面。
![123](https://github.com/user-attachments/assets/034d79e0-3f26-43d0-8242-4f8189ffcc03)

**Comment by LauZzL** [comment]
node pkg
